### PR TITLE
Fix diff output to display removals before additions

### LINKED ISSUE #12: Change modified hunk display from +/- to -/+
Most diff tools display removed lines before added lines when displaying hunks for modified lines.

Current output:

```
+ bar
- foo
```

Expected output:

```
- foo
+ bar
```

### PR DESCRIPTION
**Pull request by snusnu**
Fix #12 by switching around the order in which added and removed lines gets printed.

### CODE REVIEW

File: src/Test/Tasty/MGolden.hs [hunk 1]
```diff
@@ -100,8 +100,8 @@ printDetails Golden{..} expected actual = ResultDetailsPrinter print
         printDiff :: Diff.Diff Text -> IO ()
         printDiff = \case
           (Diff.Both   line _) -> printLine ' ' neutralFormat line
-          (Diff.First  line)   -> printLine '+' addFormat line
           (Diff.Second line)   -> printLine '-' removeFormat line
+          (Diff.First  line)   -> printLine '+' addFormat line
```
Comment (mbj) [inline src/Test/Tasty/MGolden.hs]: @snusnu Unfortunately this approach does not work. We receive a list of `Diff` types that are of either constructor, and the order the lines are printed are not affected by the order of the pattern matches.

**Review by mbj — APPROVED** [review]
